### ISSUE TITLE
Notion calendar template and setup notes?

### ISSUE THREAD

**Issue by juanggcc** [nathan-dykstra/gcal-notion-integration#2]
Cannot find a suitable notion template, code coments are enough to setup though

**Comment by nathan-dykstra** [comment]
Sorry for taking so long with this, was pretty busy with school and other projects. I doubt you are interested anymore since Notion released their own official calendar app with Google Calendar integration, but just in case...

I published my calendar and tasks templates, here's the [calendar template link](https://nathan-dykstra-personal.notion.site/3414bbbb4d6a4766b2691f6a5ba55263?v=b3228cb5c87f4f9ea88d027ee632f2a1&pvs=73)
